table_name,trigger_name,action_timing,event_manipulation,action_statement
buckets,enforce_bucket_name_length_trigger,BEFORE,UPDATE,EXECUTE FUNCTION storage.enforce_bucket_name_length()
buckets,enforce_bucket_name_length_trigger,BEFORE,INSERT,EXECUTE FUNCTION storage.enforce_bucket_name_length()
buckets,protect_buckets_delete,BEFORE,DELETE,EXECUTE FUNCTION storage.protect_delete()
checklist_templates,trg_checklist_templates_updated_at,BEFORE,UPDATE,EXECUTE FUNCTION set_updated_at()
kb_articles,trg_kb_articles_updated_at,BEFORE,UPDATE,EXECUTE FUNCTION set_updated_at()
kb_checklists,trg_kb_checklists_updated_at,BEFORE,UPDATE,EXECUTE FUNCTION touch_updated_at()
kb_templates,trg_kb_templates_updated_at,BEFORE,UPDATE,EXECUTE FUNCTION touch_updated_at()
objects,protect_objects_delete,BEFORE,DELETE,EXECUTE FUNCTION storage.protect_delete()
objects,update_objects_updated_at,BEFORE,UPDATE,EXECUTE FUNCTION storage.update_updated_at_column()
projects,trg_projects_updated_at,BEFORE,UPDATE,EXECUTE FUNCTION set_updated_at()
subscription,tr_check_filters,BEFORE,INSERT,EXECUTE FUNCTION realtime.subscription_check_filters()
subscription,tr_check_filters,BEFORE,UPDATE,EXECUTE FUNCTION realtime.subscription_check_filters()
tasks,trg_tasks_updated_at,BEFORE,UPDATE,EXECUTE FUNCTION set_updated_at()
users,on_auth_user_created,AFTER,INSERT,EXECUTE FUNCTION handle_new_user()